### ISSUE TITLE
Older Windows operation systems

### ISSUE THREAD

**Issue by rts18** [avsaase/walksnail-osd-tool#20]
I can only get the application to work on the later versions of Windows 10, and Windows 11.
The program will install on Windows 7 and Windows 8.1. But it will only try to run for a few seconds, then gives up. With no indication of why.

It would be useful to have this application working with older Windows operation systems, on laptops that we take out with us flying.

**Comment by avsaase** [comment]
Can you share the log file. It should be stored in `~\AppData\Roaming\Walksnail OSD Tool\data\`.

**Comment by rts18** [comment]
@avsaase  This is a log from Windows 7.
[walksnail-osd-tool.log](https://github.com/avsaase/walksnail-osd-tool/files/11302550/walksnail-osd-tool.log)

**Comment by avsaase** [comment]
This looks like a problem caused by old graphics drivers. You can try to update them but if there is no more recent version (Windows 7 and 81 are EOL since the start of this year) then there's not much I can do.

**Comment by rts18** [comment]
Thanks for taking a look.
