### ISSUE TITLE
HD fonts won't load.

### ISSUE THREAD

**Issue by vad7** [avsaase/walksnail-osd-tool#34]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Software version

v0.2.0

### What operating system are you using?

Windows 10

### What problem did you encounter?

These fonts are not loading - https://github.com/jduerr/Custom-Walksnail-OSD-Fonts/blob/main/user_bf_36.png
user_bf_24.png is loaded fine but then the OSD is not full screen and there is no zoom in the program.

![scr](https://github.com/avsaase/walksnail-osd-tool/assets/6220128/457c4bb9-7097-440c-a881-3214fa1c630e)

**Comment by avsaase** [comment]
Can you try the latest dev build? https://nightly.link/avsaase/walksnail-osd-tool/workflows/release.yaml/master/walksnail-osd-tool-all-platforms.zip
