### ISSUE TITLE
Wrong Crosshair

### ISSUE THREAD

**Issue by Grogdunn** [avsaase/walksnail-osd-tool#36]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Software version

master

### What operating system are you using?

Linux Mint 21.2 Victoria

### What GPU are you using?

nvidia 2070 super

### What problem did you encounter?

The crosshair is "wrong". With all font I've found is always wrong. I've converted a mcm to png to check but nothing changed.

### Link to screenshots

![image](https://github.com/avsaase/walksnail-osd-tool/assets/1835609/4ffec996-ac4a-493f-978f-e950f7fdad8b)

**Comment by avsaase** [comment]
You're using a ArduPilot font with DVR from a Betaflight flight controller.

**Comment by Grogdunn** [comment]
same using user_bf_36.png 
![image](https://github.com/avsaase/walksnail-osd-tool/assets/1835609/a6e2cb9f-fc22-42e3-a580-d51712e785be)


I've checked your code and seems ok, a different font is used (but I don't know where it is)

**Comment by Grogdunn** [comment]
I'll send to you an email with mega.nz link to download all

**Comment by Grogdunn** [comment]
maybe must support this file format? 
https://github.com/betaflight/betaflight-configurator/blob/master/resources/osd/2/betaflight.png

**Comment by Grogdunn** [comment]
Found as said before there are a different font. I've extracted this from https://github.com/betaflight/betaflight-configurator/blob/master/resources/osd/2/default.mcm

![default-bf-2-36](https://github.com/avsaase/walksnail-osd-tool/assets/1835609/df77a158-dcb9-4944-bb8e-72b3f04471c9)

and the result is:
![image](https://github.com/avsaase/walksnail-osd-tool/assets/1835609/59eddaf0-41c5-4cd6-b33b-6747c4c23e03)

seems correct!

**Comment by Grogdunn** [comment]
Thx tomorrow I'll check how to change font in osd (never done before)

**Comment by Grogdunn** [comment]
I'll close this issue. Not relevant for the software. Thansk for the advice.
