### ISSUE TITLE
Add Font Support for "Race Mode" 960x540

### ISSUE THREAD

**Issue by rickgode** [avsaase/walksnail-osd-tool#38]
### Is there an existing feature request for this?

- [X] I have searched the existing open and closed issues

### Feature description

With the firmware 34.40.15, they introduced "Race Mode"  It's 540p and video rendered with the OSD tool cuts off the fonts.  There is a slider for the SRT Options that adjusts the size.  Maybe something could be added like that for the OSD Options?

Thanks!

**Comment by mmosca** [comment]
#43 should help.

**Comment by mmosca** [comment]
@rickgode can you check 0.3.0?

**Comment by rickgode** [comment]
Well Done!  works perfectly and upscales to 1440!  GREAT IMPROVEMENT!

This is how it looks now.
![newAvatarG0005](https://github.com/avsaase/walksnail-osd-tool/assets/44140881/8243113d-adc7-4df2-9506-838c63dd3e69)

This was how it used to look where the OSD fonts didn't scale properly
![oldAvatarG0005](https://github.com/avsaase/walksnail-osd-tool/assets/44140881/0abd321c-2a57-421f-9128-2e211036ff37)

Thanks again!

**Comment by mmosca** [comment]
@avsaase this one can be closed
