### ISSUE TITLE
 Selection of displayed parameters

### ISSUE THREAD

**Issue by smithpl2000** [avsaase/walksnail-osd-tool#55]
### Is there an existing feature request for this?

- [X] I have searched the existing open and closed issues

### Feature description

Allows you to uncheck which parameters should not be applied to the image.
Possibility to remove Crosshair from the video

**Comment by avsaase** [comment]
Unfortunately this is not possible. The OSD file only contains data which character to draw where and when. The file does not contain information about OSD elements so it's not possible for the tool to mask certain elements like the crosshair.
